<?php

declare(strict_types=1);

/*
 * AgNciaVirtualV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AgNciaVirtualV2Lib\Models;

use stdClass;

class HMLAutenticarClienteRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $matricula;

    /**
     * @var string
     */
    private $documento;

    /**
     * @param string $matricula
     * @param string $documento
     */
    public function __construct(string $matricula, string $documento)
    {
        $this->matricula = $matricula;
        $this->documento = $documento;
    }

    /**
     * Returns Matricula.
     */
    public function getMatricula(): string
    {
        return $this->matricula;
    }

    /**
     * Sets Matricula.
     *
     * @required
     * @maps matricula
     */
    public function setMatricula(string $matricula): void
    {
        $this->matricula = $matricula;
    }

    /**
     * Returns Documento.
     */
    public function getDocumento(): string
    {
        return $this->documento;
    }

    /**
     * Sets Documento.
     *
     * @required
     * @maps documento
     */
    public function setDocumento(string $documento): void
    {
        $this->documento = $documento;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return mixed
     */
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['matricula'] = $this->matricula;
        $json['documento'] = $this->documento;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
