<?php

declare(strict_types=1);

/*
 * AgNciaVirtualV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AgNciaVirtualV2Lib\Models;

use stdClass;

class HMLObterTokenRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $grantType;

    /**
     * @param string $grantType
     */
    public function __construct(string $grantType)
    {
        $this->grantType = $grantType;
    }

    /**
     * Returns Grant Type.
     */
    public function getGrantType(): string
    {
        return $this->grantType;
    }

    /**
     * Sets Grant Type.
     *
     * @required
     * @maps grant_type
     */
    public function setGrantType(string $grantType): void
    {
        $this->grantType = $grantType;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return mixed
     */
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['grant_type'] = $this->grantType;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
