<?php

declare(strict_types=1);

/*
 * AgNciaVirtualV2Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AgNciaVirtualV2Lib;

/**
 * Default values for the configuration parameters of the client.
 */
class ConfigurationDefaults
{
    public const TIMEOUT = 0;

    public const ENVIRONMENT = Environment::PRODUCTION;

    public const BASIC_AUTH_USER_NAME = '';

    public const BASIC_AUTH_PASSWORD = '';
}
